#!/bin/bash

sudo docker run -d \
                -p 27017:27017 \
                -v /srv/mongo/data:/data/db \
                -v /srv/mongo/logs:/var/log/mongodb \
                --name $2 \
                $1
